### ISSUE TITLE
The script doesn't work.

### ISSUE THREAD

**Issue by zudoo** [Minewolf/Issues#5]

**Comment by inventor02** [comment]
Working on providing hosting for script, bear with me.

**Comment by zudoo** [comment]
@inventor02 NUUU THE CLIENT SCRIPT NOT THE BOT

**Comment by inventor02** [comment]
*commits suicide* inventor were u high?

**Comment by DeRpYsApLiNg** [comment]
Not worth fixing just to use it for 2-3 hours ;3 Plug.dj is rip. Will we be moving to dub track?

**Comment by inventor02** [comment]
@DeRpYsApLiNg I think this is for the Client Script (like plugCubed) at Minewolf/plug

**Comment by DeRpYsApLiNg** [comment]
@inventor02 No point fixing it is plug.dj is dead now :P

**Comment by zudoo** [comment]
plug.dj is rip, closing this :cry:
